### PR TITLE
fixed plugin.xml

### PR DESCRIPTION
**Pull request by nemanja010**

### CODE REVIEW

**Comment by cakuki** [comment]
Thanks for sending a fix!

I assume set-viewport was not called in your setup, is that correct?

I want to make sure this is not breaking or creating warnings for other platforms before merging & releasing a change like this. Do you happen to have a setup to test it with other platforms in the Cordova project?

**Comment by nemanja010** [comment]
It appeared so, but I might have misunderstood how hooks work in Cordova, and haven't tested it in details. It didn't modify the main activity file after running `cordova prepare`, but it looks like it did after running `cordova build`. Is this per design, or should the file modified after `prepare` action is called in isolation, as well?

I will try to reproduce the problem again, but at the moment, it looks like it might be just me using it wrongly.

**Comment by cakuki** [comment]
> It appeared so, but I might have misunderstood how hooks work in Cordova, and haven't tested it in details. It didn't modify the main activity file after running `cordova prepare`, but it looks like it did after running `cordova build`. Is this per design, or should the file modified after `prepare` action is called in isolation, as well?

I used Cordova 6 years ago, so hard to remember 😅

@nemanja010 if this is blocking your process I can just merge & release until it breaks someone else's. I am not sure this plugin is used that frequently.

**Comment by nemanja010** [comment]
> I used Cordova 6 years ago, so hard to remember 😅

I know that feeling.
Thanks, but it's definitely not blocking me, since the project is on hold for a bit, and it did work last time I tried it. It looks like I just misunderstood how hooks work, as explained in my previous answer. 

I think it's safe to just close the pull request.

**Comment by cakuki** [comment]
> I know that feeling. Thanks, but it's definitely not blocking me, since the project is on hold for a bit, and it did work last time I tried it. It looks like I just misunderstood how hooks work, as explained in my previous answer.
> 
> I think it's safe to just close the pull request.

Thanks a lot for following up @nemanja010! I am closing the PR but feel free to drop a message if it becomes a problem.

**Pull request closed without merging**
